==============================================================================
20220414 12:31:23.721 - INFO - + START SUITE: Callback Tests [ ]
==============================================================================
20220414 12:31:23.722 - INFO - +- START TEST: Capif Callback Server Test Case [ ]
------------------------------------------------------------------------------
20220414 12:31:23.723 - INFO - +-- START KEYWORD: BuiltIn.Run Keyword [ capifcallback ]
20220414 12:31:23.724 - INFO - +--- START KEYWORD: capifcallback [ ]
20220414 12:31:23.724 - INFO - +---- START KEYWORD: RequestsLibrary.Create Session [ mysession | ${CAPIF_HOSTNAME} | verify=True ]
20220414 12:31:23.725 - INFO - Creating Session using : alias=mysession, url=http://dummy-netapp_capif_callback_server_1:8080, headers={},                     cookies={}, auth=None, timeout=None, proxies=None, verify=True,                     debug=0
20220414 12:31:23.726 - DEBUG - Creating session: mysession
20220414 12:31:23.726 - INFO - +---- END KEYWORD: RequestsLibrary.Create Session (2)
20220414 12:31:23.727 - INFO - +---- START KEYWORD: RequestsLibrary.POST On Session [ mysession | /capifcallbacks ]
20220414 12:31:23.733 - INFO - POST Request : url=http://dummy-netapp_capif_callback_server_1:8080/capifcallbacks 
 path_url=/capifcallbacks 
 headers={'User-Agent': 'python-requests/2.22.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '0'} 
 body=None
20220414 12:31:23.734 - INFO - POST Response : url=http://dummy-netapp_capif_callback_server_1:8080/capifcallbacks 
 status=400, reason=BAD REQUEST 
 headers={'Server': 'Werkzeug/2.1.1 Python/3.10.4', 'Date': 'Thu, 14 Apr 2022 12:31:23 GMT', 'Content-Type': 'text/html; charset=utf-8', 'Content-Length': '150'} 
 body=<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>400 Bad Request</title>
<h1>Bad Request</h1>
<p>Failed to decode JSON object: None</p>
20220414 12:31:23.735 - FAIL - HTTPError: 400 Client Error: BAD REQUEST for url: http://dummy-netapp_capif_callback_server_1:8080/capifcallbacks
20220414 12:31:23.736 - DEBUG - Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/RequestsLibrary/utils.py", line 154, in decorator
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/RequestsLibrary/RequestsOnSessionKeywords.py", line 62, in post_on_session
    self._check_status(expected_status, response, msg)
  File "/usr/local/lib/python3.8/dist-packages/RequestsLibrary/SessionKeywords.py", line 570, in _check_status
    resp.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: BAD REQUEST for url: http://dummy-netapp_capif_callback_server_1:8080/capifcallbacks
20220414 12:31:23.736 - INFO - +---- END KEYWORD: RequestsLibrary.POST On Session (9)
20220414 12:31:23.739 - INFO - +---- START KEYWORD: return ${resp} [ ]
20220414 12:31:23.739 - INFO - +---- END KEYWORD: return ${resp} (0)
20220414 12:31:23.740 - INFO - +--- END KEYWORD: capifcallback (16)
20220414 12:31:23.740 - INFO - +-- END KEYWORD: BuiltIn.Run Keyword (17)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
20220414 12:31:23.741 - INFO - +-- START KEYWORD: BuiltIn.Should Contain [ ${resp} | 201 ]
20220414 12:31:23.742 - INFO - +-- END KEYWORD: BuiltIn.Should Contain (0)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
20220414 12:31:23.742 - INFO - +-- START KEYWORD: BuiltIn.Log To Console [ ${resp.message} ]
20220414 12:31:23.742 - INFO - +-- END KEYWORD: BuiltIn.Log To Console (0)
------------------------------------------------------------------------------
20220414 12:31:23.744 - INFO - +- END TEST: Capif Callback Server Test Case (21)
------------------------------------------------------------------------------
20220414 12:31:23.745 - INFO - +- START TEST: Nef Callback Server Test Case [ ]
------------------------------------------------------------------------------
20220414 12:31:23.746 - INFO - +-- START KEYWORD: BuiltIn.Run Keyword [ nefcallback ]
20220414 12:31:23.746 - INFO - +--- START KEYWORD: nefcallback [ ]
20220414 12:31:23.747 - INFO - +---- START KEYWORD: RequestsLibrary.Create Session [ mysession | ${NEF_HOSTNAME} | verify=True ]
20220414 12:31:23.748 - INFO - Creating Session using : alias=mysession, url=http://dummy-netapp_nef_callback_server_1:8080, headers={},                     cookies={}, auth=None, timeout=None, proxies=None, verify=True,                     debug=0
20220414 12:31:23.748 - DEBUG - Creating session: mysession
20220414 12:31:23.748 - INFO - +---- END KEYWORD: RequestsLibrary.Create Session (1)
20220414 12:31:23.749 - INFO - +---- START KEYWORD: RequestsLibrary.POST On Session [ mysession | /nefcallbacks ]
20220414 12:31:23.753 - INFO - POST Request : url=http://dummy-netapp_nef_callback_server_1:8080/nefcallbacks 
 path_url=/nefcallbacks 
 headers={'User-Agent': 'python-requests/2.22.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '0'} 
 body=None
20220414 12:31:23.753 - INFO - POST Response : url=http://dummy-netapp_nef_callback_server_1:8080/nefcallbacks 
 status=400, reason=BAD REQUEST 
 headers={'Server': 'Werkzeug/2.1.1 Python/3.10.4', 'Date': 'Thu, 14 Apr 2022 12:31:23 GMT', 'Content-Type': 'text/html; charset=utf-8', 'Content-Length': '150'} 
 body=<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>400 Bad Request</title>
<h1>Bad Request</h1>
<p>Failed to decode JSON object: None</p>
20220414 12:31:23.754 - FAIL - HTTPError: 400 Client Error: BAD REQUEST for url: http://dummy-netapp_nef_callback_server_1:8080/nefcallbacks
20220414 12:31:23.754 - DEBUG - Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/RequestsLibrary/utils.py", line 154, in decorator
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/RequestsLibrary/RequestsOnSessionKeywords.py", line 62, in post_on_session
    self._check_status(expected_status, response, msg)
  File "/usr/local/lib/python3.8/dist-packages/RequestsLibrary/SessionKeywords.py", line 570, in _check_status
    resp.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: BAD REQUEST for url: http://dummy-netapp_nef_callback_server_1:8080/nefcallbacks
20220414 12:31:23.755 - INFO - +---- END KEYWORD: RequestsLibrary.POST On Session (6)
20220414 12:31:23.757 - INFO - +---- START KEYWORD: return ${resp} [ ]
20220414 12:31:23.757 - INFO - +---- END KEYWORD: return ${resp} (0)
20220414 12:31:23.758 - INFO - +--- END KEYWORD: nefcallback (12)
20220414 12:31:23.758 - INFO - +-- END KEYWORD: BuiltIn.Run Keyword (12)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
20220414 12:31:23.759 - INFO - +-- START KEYWORD: BuiltIn.Should Contain [ ${resp} | 201 ]
20220414 12:31:23.759 - INFO - +-- END KEYWORD: BuiltIn.Should Contain (0)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
20220414 12:31:23.760 - INFO - +-- START KEYWORD: BuiltIn.Log To Console [ ${resp.message} ]
20220414 12:31:23.760 - INFO - +-- END KEYWORD: BuiltIn.Log To Console (0)
------------------------------------------------------------------------------
20220414 12:31:23.761 - INFO - +- END TEST: Nef Callback Server Test Case (17)
------------------------------------------------------------------------------
20220414 12:31:23.763 - INFO - + END SUITE: Callback Tests (107)
==============================================================================
