<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 5.0 (Python 3.8.10 on linux)" generated="20220602 09:30:16.892" rpa="false" schemaversion="3">
<suite id="s1" name="Callback Tests" source="/opt/robot-tests/tests/callbacks/callback_tests.robot">
<test id="s1-t1" name="Capif Callback Server Test Case" line="31">
<kw name="Run Keyword" library="BuiltIn">
<var>${resp}</var>
<arg>capifcallback</arg>
<doc>Executes the given keyword with the given arguments.</doc>
<kw name="capifcallback">
<kw name="Create Session" library="RequestsLibrary">
<arg>mysession</arg>
<arg>${CAPIF_HOSTNAME}</arg>
<arg>verify=True</arg>
<doc>Create Session: create a HTTP session to a server</doc>
<msg timestamp="20220602 09:30:16.969" level="INFO">Creating Session using : alias=mysession, url=http://dummy-netapp_capif_callback_server_1:8080, headers={},                     cookies={}, auth=None, timeout=None, proxies=None, verify=True,                     debug=0 </msg>
<status status="PASS" starttime="20220602 09:30:16.969" endtime="20220602 09:30:16.969"/>
</kw>
<kw name="POST On Session" library="RequestsLibrary">
<var>${resp}</var>
<arg>mysession</arg>
<arg>/capifcallbacks</arg>
<doc>Sends a POST request on a previously created HTTP Session.</doc>
<msg timestamp="20220602 09:30:20.905" level="WARN">Retrying (RetryAdapter(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7fa48c75faf0&gt;: Failed to establish a new connection: [Errno -2] Name or service not known')': /capifcallbacks</msg>
<msg timestamp="20220602 09:30:24.902" level="WARN">Retrying (RetryAdapter(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7fa48c75fd90&gt;: Failed to establish a new connection: [Errno -2] Name or service not known')': /capifcallbacks</msg>
<msg timestamp="20220602 09:30:29.173" level="WARN">Retrying (RetryAdapter(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7fa48c75ffa0&gt;: Failed to establish a new connection: [Errno -2] Name or service not known')': /capifcallbacks</msg>
<msg timestamp="20220602 09:30:32.952" level="FAIL">ConnectionError: HTTPConnectionPool(host='dummy-netapp_capif_callback_server_1', port=8080): Max retries exceeded with url: /capifcallbacks (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7fa48c6cf1c0&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</msg>
<status status="FAIL" starttime="20220602 09:30:16.969" endtime="20220602 09:30:32.964"/>
</kw>
<kw name="return ${resp}">
<status status="NOT RUN" starttime="20220602 09:30:32.966" endtime="20220602 09:30:32.966"/>
</kw>
<status status="FAIL" starttime="20220602 09:30:16.968" endtime="20220602 09:30:32.966"/>
</kw>
<status status="FAIL" starttime="20220602 09:30:16.968" endtime="20220602 09:30:32.967"/>
</kw>
<kw name="Should Contain" library="BuiltIn">
<arg>${resp}</arg>
<arg>201</arg>
<doc>Fails if ``container`` does not contain ``item`` one or more times.</doc>
<status status="NOT RUN" starttime="20220602 09:30:32.967" endtime="20220602 09:30:32.967"/>
</kw>
<kw name="Log To Console" library="BuiltIn">
<arg>${resp.message}</arg>
<doc>Logs the given message to the console.</doc>
<status status="NOT RUN" starttime="20220602 09:30:32.967" endtime="20220602 09:30:32.967"/>
</kw>
<tag>capif_callback_server</tag>
<status status="FAIL" starttime="20220602 09:30:16.967" endtime="20220602 09:30:32.968">ConnectionError: HTTPConnectionPool(host='dummy-netapp_capif_callback_server_1', port=8080): Max retries exceeded with url: /capifcallbacks (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7fa48c6cf1c0&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</status>
</test>
<test id="s1-t2" name="Nef Callback Server Test Case" line="41">
<kw name="Run Keyword" library="BuiltIn">
<var>${resp}</var>
<arg>nefcallback</arg>
<doc>Executes the given keyword with the given arguments.</doc>
<kw name="nefcallback">
<kw name="Create Session" library="RequestsLibrary">
<arg>mysession</arg>
<arg>${NEF_HOSTNAME}</arg>
<arg>verify=True</arg>
<doc>Create Session: create a HTTP session to a server</doc>
<msg timestamp="20220602 09:30:32.969" level="INFO">Creating Session using : alias=mysession, url=http://dummy-netapp_nef_callback_server_1:8080, headers={},                     cookies={}, auth=None, timeout=None, proxies=None, verify=True,                     debug=0 </msg>
<status status="PASS" starttime="20220602 09:30:32.969" endtime="20220602 09:30:32.970"/>
</kw>
<kw name="POST On Session" library="RequestsLibrary">
<var>${resp}</var>
<arg>mysession</arg>
<arg>/nefcallbacks</arg>
<doc>Sends a POST request on a previously created HTTP Session.</doc>
<status status="FAIL" starttime="20220602 09:30:32.970" endtime="20220602 09:30:36.849"/>
</kw>
<kw name="return ${resp}">
<status status="NOT RUN" starttime="20220602 09:30:36.857" endtime="20220602 09:30:36.857"/>
</kw>
<status status="FAIL" starttime="20220602 09:30:32.969" endtime="20220602 09:30:36.857"/>
</kw>
<status status="FAIL" starttime="20220602 09:30:32.969" endtime="20220602 09:30:36.857"/>
</kw>
<kw name="Should Contain" library="BuiltIn">
<arg>${resp}</arg>
<arg>201</arg>
<doc>Fails if ``container`` does not contain ``item`` one or more times.</doc>
<status status="NOT RUN" starttime="20220602 09:30:36.858" endtime="20220602 09:30:36.858"/>
</kw>
<kw name="Log To Console" library="BuiltIn">
<arg>${resp.message}</arg>
<doc>Logs the given message to the console.</doc>
<status status="NOT RUN" starttime="20220602 09:30:36.858" endtime="20220602 09:30:36.859"/>
</kw>
<tag>nef_callback_server</tag>
<status status="FAIL" starttime="20220602 09:30:32.968" endtime="20220602 09:30:36.860">Execution terminated by signal</status>
</test>
<status status="FAIL" starttime="20220602 09:30:16.896" endtime="20220602 09:30:36.862"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="2" skip="0">All Tests</stat>
</total>
<tag>
<stat pass="0" fail="1" skip="0">capif_callback_server</stat>
<stat pass="0" fail="1" skip="0">nef_callback_server</stat>
</tag>
<suite>
<stat pass="0" fail="2" skip="0" id="s1" name="Callback Tests">Callback Tests</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20220602 09:30:20.905" level="WARN">Retrying (RetryAdapter(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7fa48c75faf0&gt;: Failed to establish a new connection: [Errno -2] Name or service not known')': /capifcallbacks</msg>
<msg timestamp="20220602 09:30:24.902" level="WARN">Retrying (RetryAdapter(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7fa48c75fd90&gt;: Failed to establish a new connection: [Errno -2] Name or service not known')': /capifcallbacks</msg>
<msg timestamp="20220602 09:30:29.173" level="WARN">Retrying (RetryAdapter(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7fa48c75ffa0&gt;: Failed to establish a new connection: [Errno -2] Name or service not known')': /capifcallbacks</msg>
</errors>
</robot>
